theme: jekyll-theme-time-machine
description: Gets 6 variables (questions and answeres) and arranges them in certain orders as well as displays information about them. Information is displayed on a server.
